// frontend-svelte/src/routes/spaces/+page.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query';
  import { api } from '$lib/api/client';
  import type { Space } from '$lib/api/schemas';
  import { goto } from '$app/navigation';

  const spacesQuery = createQuery<Space[]>({
    queryKey: ['spaces'],
    queryFn: async () => api.get('spaces/').json()
  });
</script>

<div class="p-6">
  <h1 class="text-2xl font-semibold mb-4">Spaces</h1>
  {#if $spacesQuery.isLoading}
    <p>Loading...</p>
  {:else if $spacesQuery.isError}
    <p>Error loading spaces</p>
  {:else}
    <ul class="space-y-2">
      {#each $spacesQuery.data as s}
        <li>
          <button class="link" on:click={() => goto(`/spaces/${s.key}`)}>{s.name} ({s.key})</button>
        </li>
      {/each}
    </ul>
  {/if}
</div>

// frontend-next/src/app/spaces/page.tsx
"use client";
import Link from "next/link";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";

export default function SpacesPage() {
  const { data, isLoading, error } = useQuery({
    queryKey: ["spaces"],
    queryFn: () => api.get("spaces/").json<any[]>(),
  });

  if (isLoading) return <main className="p-6">Loading...</main>;
  if (error) return <main className="p-6">Failed to load spaces</main>;

  return (
    <main className="p-6">
      <h1 className="text-xl font-semibold mb-4">Spaces</h1>
      <ul className="space-y-2">
        {data?.map((s) => (
          <li key={s.key} className="border rounded p-3">
            <div className="font-medium">{s.name} ({s.key})</div>
            <div className="text-sm text-zinc-600">{s.description}</div>
            <Link className="underline text-sm" href={`/spaces/${s.key}`}>Open</Link>
          </li>
        ))}
      </ul>
    </main>
  );
}
