// frontend-svelte/src/routes/spaces/[key]/+page.svelte
<script lang="ts">
  import { createQuery } from '@tanstack/svelte-query';
  import { api } from '$lib/api/client';
  import { page } from '$app/stores';
  import type { Page as Pg } from '$lib/api/schemas';
  import { goto } from '$app/navigation';

  $: key = $page.params.key;

  const pagesQuery = createQuery<Pg[]>({
    queryKey: ['pages', key],
    queryFn: async () => api.get(`spaces/${key}/pages/`).json(),
    enabled: !!key
  });
</script>

<div class="p-6">
  <h1 class="text-2xl font-semibold mb-4">Space: {key}</h1>
  {#if $pagesQuery.isLoading}
    <p>Loading...</p>
  {:else if $pagesQuery.isError}
    <p>Error loading pages</p>
  {:else}
    <ul class="space-y-2">
      {#each $pagesQuery.data as p}
        <li>
          <button class="link" on:click={() => goto(`/spaces/${key}/pages/${p.slug}`)}>{p.title}</button>
        </li>
      {/each}
    </ul>
  {/if}
</div>

// frontend-next/src/app/spaces/[key]/page.tsx
"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useQuery } from "@tanstack/react-query";
import { api } from "@/lib/api";

export default function SpaceDetailPage() {
  const { key } = useParams<{ key: string }>();
  const { data: space } = useQuery({
    queryKey: ["space", key],
    queryFn: () => api.get(`spaces/${key}/`).json<any>(),
    enabled: !!key,
  });
  const { data: pages } = useQuery({
    queryKey: ["pages", key],
    queryFn: () => api.get("pages/", { searchParams: { space_key: key } }).json<any[]>(),
    enabled: !!key,
  });

  if (!space) return <main className="p-6">Loading...</main>;

  return (
    <main className="p-6 space-y-4">
      <h1 className="text-xl font-semibold">{space.name} ({space.key})</h1>
      <ul className="space-y-1">
        {pages?.map((p) => (
          <li key={p.id}>
            <Link className="underline" href={`/spaces/${space.key}/pages/${p.slug}`}>{p.title}</Link>
          </li>
        ))}
      </ul>
    </main>
  );
}
