// frontend-next/src/app/register/page.tsx
"use client";
import { useState } from "react";
import ky from "ky";
import { useRouter } from "next/navigation";

export default function RegisterPage() {
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState<string | null>(null);
  const router = useRouter();

  async function onSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    try {
      await ky.post("/api/users/", { json: { username, email, password } });
      router.push("/login");
    } catch (e) {
      setError("Registration failed");
    }
  }

  return (
    <main className="p-4 sm:p-6 max-w-sm mx-auto space-y-4">
      <h1 className="text-lg sm:text-xl font-semibold">Register</h1>
      {error && <p className="text-red-600 text-sm">{error}</p>}
      <form className="space-y-4" onSubmit={onSubmit}>
        <input className="w-full border border-neutral-300 dark:border-neutral-600 p-3 rounded-lg text-base bg-white dark:bg-neutral-800 text-neutral-900 dark:text-neutral-100 placeholder-neutral-400 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-h-[44px]" placeholder="Username" value={username} onChange={e=>setUsername(e.target.value)} />
        <input className="w-full border border-neutral-300 dark:border-neutral-600 p-3 rounded-lg text-base bg-white dark:bg-neutral-800 text-neutral-900 dark:text-neutral-100 placeholder-neutral-400 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-h-[44px]" placeholder="Email" type="email" value={email} onChange={e=>setEmail(e.target.value)} />
        <input className="w-full border border-neutral-300 dark:border-neutral-600 p-3 rounded-lg text-base bg-white dark:bg-neutral-800 text-neutral-900 dark:text-neutral-100 placeholder-neutral-400 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-h-[44px]" type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} />
        <button className="bg-blue-600 hover:bg-blue-700 text-white px-4 py-3 rounded-lg w-full font-medium disabled:opacity-50 min-h-[44px]" type="submit">Create account</button>
      </form>
    </main>
  );
}

// frontend-svelte/src/routes/register/+page.svelte
<script lang="ts">
  import { createMutation } from '@tanstack/svelte-query';
  import { api } from '$lib/api/client';
  import { goto } from '$app/navigation';

  let username = '';
  let password = '';

  const mutation = createMutation({
    mutationFn: async () => {
      await api.post('auth/register/', { json: { username, password } });
    },
    onSuccess: () => goto('/login')
  });
</script>

<div class="container mx-auto max-w-md px-4 sm:px-6 py-6 sm:py-10">
  <h1 class="text-xl sm:text-2xl font-semibold mb-4">Register</h1>
  <form on:submit|preventDefault={() => mutation.mutate()} class="space-y-3">
    <input
      class="w-full border border-neutral-300 dark:border-neutral-600 rounded px-3 py-3 bg-transparent text-base focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-h-[44px]"
      placeholder="Username"
      autocomplete="username"
      bind:value={username}
    />
    <input
      class="w-full border border-neutral-300 dark:border-neutral-600 rounded px-3 py-3 bg-transparent text-base focus:ring-2 focus:ring-blue-500 focus:border-blue-500 outline-none min-h-[44px]"
      placeholder="Password"
      type="password"
      autocomplete="new-password"
      bind:value={password}
    />
    <button
      class="w-full px-4 py-3 rounded bg-blue-600 text-white font-medium disabled:opacity-60 hover:bg-blue-700 active:bg-blue-800 transition-colors min-h-[44px]"
      disabled={mutation.isPending}
    >
      Register
    </button>
    {#if mutation.isError}
      <p class="text-red-500 text-sm">Registration failed</p>
    {/if}
    <p class="text-sm text-neutral-500 text-center">
      Already have an account? <a href="/login" class="text-blue-600 dark:text-blue-400 underline">Login</a>
    </p>
  </form>
</div>
