// frontend-svelte/src/lib/components/ResponsiveTable.svelte
<!--
  ResponsiveTable — wraps table content so it scrolls horizontally on small screens
  while using full-width on desktop. Mirrors the React ResponsiveTable component.
-->
<script lang="ts">
  import { onMount } from 'svelte';

  export let className: string = '';
  /** Label for screen-reader users describing the scrollable region */
  export let label: string = 'Scrollable table';
  /**
   * Background variant for gradient overlays — must match the parent surface.
   * 'card' (default) = white / neutral-900 card backgrounds
   * 'surface' = neutral-50 / neutral-950 page backgrounds
   */
  export let bg: 'card' | 'surface' = 'card';

  const gradientColors: Record<string, string> = {
    card: 'from-white dark:from-neutral-900',
    surface: 'from-neutral-50 dark:from-neutral-950',
  };

  let scrollEl: HTMLDivElement;
  let canScrollLeft = false;
  let canScrollRight = false;

  function updateScrollState() {
    if (!scrollEl) return;
    canScrollLeft = scrollEl.scrollLeft > 1;
    canScrollRight = scrollEl.scrollLeft + scrollEl.clientWidth < scrollEl.scrollWidth - 1;
  }

  onMount(() => {
    updateScrollState();
    const ro = new ResizeObserver(updateScrollState);
    ro.observe(scrollEl);
    scrollEl.addEventListener('scroll', updateScrollState, { passive: true });
    return () => {
      ro.disconnect();
      scrollEl.removeEventListener('scroll', updateScrollState);
    };
  });

  $: from = gradientColors[bg];
  $: scrollHint = canScrollLeft || canScrollRight
    ? `${label} — scroll horizontally to see more`
    : label;
</script>

<div class="relative {className}" role="region" aria-label={label}>
  {#if canScrollLeft}
    <div class="absolute left-0 top-0 bottom-0 w-4 sm:w-6 bg-gradient-to-r {from} to-transparent z-10 pointer-events-none" aria-hidden="true" />
  {/if}
  {#if canScrollRight}
    <div class="absolute right-0 top-0 bottom-0 w-4 sm:w-6 bg-gradient-to-l {from} to-transparent z-10 pointer-events-none" aria-hidden="true" />
  {/if}
  <div
    bind:this={scrollEl}
    tabindex="0"
    class="overflow-x-auto -mx-4 sm:-mx-6 md:mx-0 scrollbar-thin"
    aria-label={scrollHint}
  >
    <div class="inline-block min-w-full px-4 sm:px-6 md:px-0 align-middle">
      <slot />
    </div>
  </div>
</div>

// frontend-next/src/components/ResponsiveTable.tsx
"use client";
import { useRef, useState, useEffect, useCallback } from "react";

interface ResponsiveTableProps {
  children: React.ReactNode;
  className?: string;
  label?: string;
  bg?: "card" | "surface";
}

const gradientColors = {
  card: "from-white dark:from-neutral-900",
  surface: "from-neutral-50 dark:from-neutral-950",
};

export default function ResponsiveTable({
  children,
  className = "",
  label = "Scrollable table",
  bg = "card",
}: ResponsiveTableProps) {
  const scrollRef = useRef<HTMLDivElement>(null);
  const [canScrollLeft, setCanScrollLeft] = useState(false);
  const [canScrollRight, setCanScrollRight] = useState(false);

  const updateScrollState = useCallback(() => {
    const el = scrollRef.current;
    if (!el) return;
    setCanScrollLeft(el.scrollLeft > 1);
    setCanScrollRight(el.scrollLeft + el.clientWidth < el.scrollWidth - 1);
  }, []);

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    updateScrollState();
    el.addEventListener("scroll", updateScrollState, { passive: true });
    const ro = new ResizeObserver(updateScrollState);
    ro.observe(el);
    return () => {
      el.removeEventListener("scroll", updateScrollState);
      ro.disconnect();
    };
  }, [updateScrollState]);

  const from = gradientColors[bg];
  const scrollHint =
    canScrollLeft || canScrollRight
      ? `${label} — scroll horizontally to see more`
      : label;

  return (
    <div className={`relative ${className}`} role="region" aria-label={label}>
      {canScrollLeft && (
        <div
          className={`absolute left-0 top-0 bottom-0 w-4 sm:w-6 bg-gradient-to-r ${from} to-transparent z-10 pointer-events-none`}
          aria-hidden="true"
        />
      )}
      {canScrollRight && (
        <div
          className={`absolute right-0 top-0 bottom-0 w-4 sm:w-6 bg-gradient-to-l ${from} to-transparent z-10 pointer-events-none`}
          aria-hidden="true"
        />
      )}
      <div
        ref={scrollRef}
        tabIndex={0}
        className="overflow-x-auto -mx-4 sm:-mx-6 md:mx-0 scrollbar-thin"
        aria-label={scrollHint}
      >
        <div className="inline-block min-w-full px-4 sm:px-6 md:px-0 align-middle">
          {children}
        </div>
      </div>
    </div>
  );
}
